docker:
  image: yegor256/java8
install: |-
  sudo locale-gen en_US en_US.UTF-8
  sudo dpkg-reconfigure locales
  export LC_ALL=en_US.UTF-8
  export LANG=en_US.UTF-8
  export LANGUAGE=en_US.UTF-8
  sudo apt-get install bsdmainutils
  env
  alias
  ruby --version
  sudo ruby --version
  sudo -i ruby --version
  sudo env
  sudo gem install --no-rdoc --no-ri pdd est
  # see https://gist.github.com/telbiyski/ec56a92d7114b8631c906c18064ce620
  sudo apt-get update
  sudo apt-get install build-essential chrpath libssl-dev libxft-dev -y
  sudo apt-get install libfreetype6 libfreetype6-dev -y
  sudo apt-get install libfontconfig1 libfontconfig1-dev -y
  export PHANTOM_JS="phantomjs-2.1.1-linux-x86_64"
  wget https://github.com/Medium/phantomjs/releases/download/v2.1.1/$PHANTOM_JS.tar.bz2
  tar xvjf $PHANTOM_JS.tar.bz2
  rm $PHANTOM_JS.tar.bz2
  sudo mv $(pwd)/$PHANTOM_JS /usr/local/share
  sudo ln -sf /usr/local/share/$PHANTOM_JS/bin/phantomjs /usr/local/bin
  phantomjs --version
architect:
- yegor256
- alex-palevsky
assets:
  secring.gpg: zerocracy/home#assets/secring.gpg
  id_rsa: zerocracy/home#assets/heroku-key
  settings.xml: zerocracy/home#assets/rultor/settings.xml
  pubring.gpg: zerocracy/home#assets/pubring.gpg
  id_rsa.pub: zerocracy/home#assets/heroku-key.pub
  s3cfg: zerocracy/home#assets/s3cfg
merge:
  fast-forward: only
  rebase: true
  script: |-
    pdd --file=/dev/null
    mvn help:system clean install -Pqulice -Prultor --errors --settings ../settings.xml
    mvn clean site -Psite --errors --settings ../settings.xml --quiet
    mvn clean
  commanders:
  - carlosmiranda
  - dmzaytsev
  - essobedo
  - ggajos
  - hdouss
  - krzyk
  - longtimeago
  - mkordas
  - pinaf
  - filfreire
deploy:
  script: |-
    mvn clean package -Prultor --errors --settings ../settings.xml --batch-mode --quiet
    mvn clean
    est --dir=./est --verbose --file=rultor.xml --format=xml
    s3cmd --no-progress put rultor.xml --config=../s3cfg s3://est.teamed.io/rultor.xml
env:
  MAVEN_OPTS: -XX:MaxPermSize=256m -Xmx1g
release:
  pre: false
  script: |-
    echo "Author of the request: ${author}"
    mvn versions:set "-DnewVersion=${tag}" --quiet
    git commit -am "${tag}"
    cp ../settings.xml settings.xml
    mvn clean package -Pqulice -Prultor --errors --batch-mode --quiet
    git remote add heroku git@heroku.com:rultor.git
    mkdir -p ~/.ssh
    mv ../id_rsa ../id_rsa.pub ~/.ssh
    chmod -R 600 ~/.ssh/*
    echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null" > ~/.ssh/config
    build=$(git rev-parse --short HEAD)
    sed -i "s/BUILD/${build}/g" src/main/resources/META-INF/MANIFEST.MF
    sed -i "s/BUILD/${build}/g" src/main/resources/log4j.properties
    git add src/main/resources/META-INF/MANIFEST.MF
    git add src/main/resources/log4j.properties
    git commit -m 'build number set'
    git add settings.xml
    git commit -m 'settings.xml' && git push -f heroku $(git symbolic-ref --short HEAD):master && git reset HEAD~1
    curl -f --connect-timeout 30 --retry 8 --retry-delay 60 http://www.rultor.com
    mvn clean site-deploy -Prultor -Psite --errors --settings ../settings.xml --batch-mode || echo 'site-deploy failed'
  commanders:
  - yegor256
